#!/bin/sh
# shellcheck disable=SC2006
# Purpose:   Build file lists for use by simple-locate
# Author:    Rawiri Blundell
# Copyright: MIT licence
# Date:      20160503

# Style note: This uses awful backticks for SVR4 compatibility

# Select a destination directory
destDir=/var/lib/simple-locate

# Filesystem types to ignore.  Built up from Linux and Solaris so far...
# Try to keep it alphabetical if you add anything...
exclFS="afs autofs coda ctfs dev devfs devpts fd ftpfs hsfs iso9660 lofs mfs mntfs namefs ncpfs nfs NFS objfs pcfs proc shfs smbfs sysfs tmpfs uvfs"

# We convert this to a find friendly list too
pruneFS=
for fs in ${exclFS}; do
  pruneFS="${pruneFS} -o -fstype ${fs}"
done
# Now we chop off the unwanted "-o" at the start of the variable
pruneFS=`echo "${pruneFS}" | cut -d " " -f3-`

# Directories to ignore.  Built up from Linux and Solaris so far...
# Try to keep it alphabetical if you add anything...
exclPaths="/afs /amd /cdrom /media /proc /sfs /tmp /usr/tmp /var/tmp"

# Now we convert this to a list we can use in find.
# We basically want to convert "/afs /amd ..." 
# to "-o -fstype d -name /afs -o -fstype d -name /amd ..."

# There's very likely a non-portable, very elegant way to do this with 'sed' or 'awk'

# We start by blanking out a new variable
prunePaths=

# Then for each item in the exclPaths list, we build up the new variable
for path in ${exclPaths}; do
  prunePaths="${prunePaths} -o -type d -name ${path}"
done

# Figure out our tmp directory.  We want any existing index files to be available 
# during generation of the new ones.  So we build into tmp then move into place
if [ -d /tmp ]; then
  tmpDir=/tmp
elif [ -d /var/tmp ]; then
  tmpDir=/var/tmp
elif [ -d /usr/tmp ]; then
  tmpDir=/usr/tmp
fi

# This one can't be blank
if [ -z "${tmpDir}" ]; then
  printf "%s\n" "[ERROR]: Unable to determine the tmp directory on this system."
  exit 1
fi

# Ensure the destination directory exists
if [ ! -d "${destDir}" ]; then
  if [ ! -w "${destDir}" ]; then
    destDir="${tmpDir}"
  else
    mkdir -p "${destDir}"
    # TO-DO: ensure correct permissions/ownership?
  fi
fi

# If we're running as root, we can generate both files
if [ -w / ]; then
  # Create our root-readable file
  # shellcheck disable=SC2086
  find / \( ${pruneFS}${prunePaths} \) -prune -o -print 2>/dev/null > "${tmpDir}"/locate.root
  
  # Ensure correct ownership and permissions
  chown root:root "${tmpDir}"/locate.root
  chmod 440 "${tmpDir}"/locate.root

  # Create our user-readable file.  We use -s to override /bin/false or /bin/nologin
  # This should remove most files that aren't accessible to users, without
  # needing to stat/test every file
  su -s /bin/sh nobody -c "find / \( ${pruneFS}${prunePaths} \) -prune -o -print 2>/dev/null > ${tmpDir}/locate.user"

  # Ensure correct ownership and permissions
  chmod 444 "${tmpDir}"/locate.user

# Otherwise, we just generate what we can (i.e. manual run)
else
  # This will list files limited to the invocating user
  printf "%s\n" "INFO: building index now, this may take a while..."
  # shellcheck disable=SC2086
  find / \( ${pruneFS}${prunePaths} \) -prune -o -print 2>/dev/null > ${tmpDir}/locate.user

  # Ensure correct ownership and permissions
  chmod 444 "${tmpDir}"/locate.user
fi

# If tmpDir and destDir are different, move the tmp files to the destination
if [ ! "${tmpDir}" = "${destDir}" ]; then
  mv "${tmpDir}"/locate.root "${destDir}"
  mv "${tmpDir}"/locate.user "${destDir}"
fi
